[proxmox_nodes]
192.168.0.30 ansible_user=ansible
192.168.0.31 ansible_user=ansible
192.168.0.32 ansible_user=root



# BEGIN AUTO_MANAGED_GUESTS



# BEGIN AUTO_MANAGED_GUESTS
[lxc_containers]
adguard ansible_host=192.168.0.49 # adguard (pve1:118)
ansible ansible_host=192.168.0.113 # Ansible (pve3:113)
cockpit ansible_host=192.168.0.6 # cockpit (pve1:130)
exitnode ansible_host=192.168.0.100 # exitnode (pve1:100)
graylog ansible_host=192.168.0.117 # graylog (pve2:117)
homarr ansible_host=192.168.0.121 # homarr (pve3:121)
homepage ansible_host=192.168.0.104 # homepage (pve3:104)
myspeed ansible_host=192.168.0.125 # myspeed (pve1:125)
netbootxyz ansible_host=192.168.0.105 # netbootxyz (pve1:105)
netbox ansible_host=192.168.0.109 # netbox (pve2:109)
nextcloudpi ansible_host=192.168.0.103 # nextcloudpi (pve2:103)
nginxproxymanager ansible_host=192.168.0.107 # nginxproxymanager (pve1:107)
ntfy ansible_host=192.168.0.119 # ntfy (pve1:119)
ollama ansible_host=192.168.0.129 # ollama (pve3:129)
omada ansible_host=192.168.0.108 # omada (pve1:108)
openwebui ansible_host=192.168.0.132 # openwebui (pve3:132)
paperless_ai ansible_host=192.168.0.122 # paperless-ai (pve2:122)
paperless_gpt ansible_host=192.168.0.124 # paperless-gpt (pve2:124)
paperless_ngx ansible_host=192.168.0.116 # paperless-ngx (pve2:116)
patchmon ansible_host=192.168.0.115 # patchmon (pve2:115)
phpipam ansible_host=192.168.0.102 # phpipam (pve2:102)
reactive_resume ansible_host=192.168.0.111 # reactive-resume (pve3:111)
rustdeskserver ansible_host=192.168.0.106 # rustdeskserver (pve2:106)
scanopy ansible_host=192.168.0.120 # scanopy (pve2:120)
semaphore ansible_host=192.168.0.114 # semaphore (pve3:114)
stirling_pdf ansible_host=192.168.0.112 # stirling-pdf (pve2:112)
syncthing ansible_host=192.168.0.110 # syncthing (pve1:110)
tandoor ansible_host=192.168.0.123 # tandoor (pve2:123)
uptimekuma ansible_host=192.168.0.126 # uptimekuma (pve1:126)

[vms]
haos15_2 ansible_host=192.168.0.101 # haos15.2 (pve1:101)
# END AUTO_MANAGED_GUESTS
