---
- hosts: all
  become: false
  tasks:
    - name: Clone dotfiles repository to home directory
      ansible.builtin.git:
        repo: git@github.com:jcnichols22/dotfiles.git
        dest: ~/dotfiles
        accept_hostkey: yes
        # If you have a custom SSH key, add: key_file: /path/to/ssh/key
        # If you forward your agent, ensure ssh-agent forwarding is enabled in ansible.cfg[1][3][4]

    - name: Symlink .bash_aliases to home directory
      ansible.builtin.file:
        src: ~/dotfiles/.bash_aliases
        dest: ~/.bash_aliases
        state: link
