---
- name: Update Ubuntu servers
  hosts: proxmox_servers, media_server
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
