# This role sets up a media server environment on Ubuntu, installing necessary packages and cloning a repository for the docker compose files.

- name: Install required packages
  apt:
    name: "{{ media_server_packages }}"
    state: present
  when: ansible_distribution == "Ubuntu"
  tags: packages

- name: Clone media server repository
  git:
    repo: "{{ media_repo }}"
    dest: "{{ media_repo_dest }}"
    version: main
    update: yes
    force: yes
  become: yes
  become_user: "{{ media_user }}"
  when: ansible_distribution == "Ubuntu"
  tags: repo