---
- name: Clone dotfiles repo and link .bash_aliases
  hosts: all
  vars:
    repo_url: "https://github.com/jcnichols22/dotfiles.git"
    clone_dest: "{{ ansible_env.HOME }}/dotfiles"
    link_src: "{{ clone_dest }}/.bash_aliases"
    link_dest: "{{ ansible_env.HOME }}/.bash_aliases"
  tasks:
    - name: Clone dotfiles repository to home directory
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_dest }}"
        update: yes

    - name: Create symlink for .bash_aliases in home directory
      ansible.builtin.file:
        src: "{{ link_src }}"
        dest: "{{ link_dest }}"
        state: link
