---
# This playbook is used to onboard a new server by installing necessary packages, adding users, and configuring sudo permissions.

- name: Onboarding
  hosts: all
  become: true
  vars_files:
    - users.yml
  pre_tasks:
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: true

    - name: Upgrade all packages (Ubuntu/Debian)
      apt:
        upgrade: dist
        autoremove: true
        autoclean: true

  roles:
    - base

- name: Workstation setup
  hosts: workstations
  become: true
  roles:
    - workstations

- name: Proxmox server setup
  hosts: proxmox_servers
  become: true
  roles:
    - proxmox_servers

- name: Media server setup
  hosts: media_servers
  become: true
  roles:
    - media_server
