---
# Combined Onboarding Playbook

- name: Onboarding for Media Servers
  hosts: media_servers
  become: true

  pre_tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: apt

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      tags: snap

    - name: Check if snap command is available
      ansible.builtin.stat:
        path: /usr/bin/snap
      register: snap_stat

  tasks:
    - name: Upgrade all snap packages
      ansible.builtin.command: snap refresh
      when: snap_stat.stat.exists
      tags: snap

  roles:
    - base
    - dotfiles
    - media_server

- name: Onboarding for Workstations
  hosts: workstations
  become: true

  pre_tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: apt

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      tags: snap

    - name: Check if snap command is available
      ansible.builtin.stat:
        path: /usr/bin/snap
      register: snap_stat

  tasks:
    - name: Upgrade all snap packages
      ansible.builtin.command: snap refresh
      when: snap_stat.stat.exists
      tags: snap

  roles:
    - base
    - dotfiles
    - workstations

- name: Onboarding for All Other Hosts
  hosts: all:!media_servers:!workstations
  become: true

  pre_tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: apt

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      tags: snap

    - name: Check if snap command is available
      ansible.builtin.stat:
        path: /usr/bin/snap
      register: snap_stat

  tasks:
    - name: Upgrade all snap packages
      ansible.builtin.command: snap refresh
      when: snap_stat.stat.exists
      tags: snap

  roles:
    - base
    - dotfiles
