---
# This playbook is used to onboard a new server by installing necessary packages, adding users, and configuring sudo permissions.

- name: Onboarding
  hosts: all
  become: true
  vars:
    users:
      - name: josh
        ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFyElCMNFojFX/mLWuIFAzKOzZlhJqgkxefOzQJ6bI/b josh default"
        sudo: true
      - name: ansible
        ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICPM8xsQ9Y+s7d5cBCBDo8lleyOui7gttZqkoEP+6MNN ansible"
        sudo: true
        nopasswd: true

  pre_tasks:
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: true

    - name: Upgrade all packages (Ubuntu/Debian)
      apt:
        upgrade: dist
        autoremove: true
        autoclean: true

  roles:
    - base

- name: Workstation setup
  hosts: workstations
  become: true
  roles:
    - workstations

- name: Proxmox server setup
  hosts: proxmox_servers
  become: true
  roles:
    - proxmox_servers

- name: Media server setup
  hosts: media_servers
  become: true
  roles:
    - media_server
