---
# what this playbook does:
# - Updates and upgrades apt packages
# - Ensures snapd is installed
# - Checks if the snap command is available
# - Upgrades all snap packages if snap is available
# - Applies roles for base setup, dotfiles, and workstations

- name: Onboarding
  hosts: workstations
  become: true

  pre_tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      become: true
      tags: apt

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      become: true
      tags: snap

    - name: Check if snap command is available
      ansible.builtin.stat:
        path: /usr/bin/snap
      register: snap_stat

  tasks:
    - name: Upgrade all snap packages
      ansible.builtin.command: snap refresh
      become: true
      when: snap_stat.stat.exists
      tags: snap

  roles:
    - base
    - dotfiles
    - workstations
