---
# This playbook is used to onboard a new server by installing necessary packages, adding users, and configuring sudo permissions.
- name: Server Onboarding
  hosts: all
  become: true
  tasks:
    - name: install sudo package
      apt:
        name: sudo
        update_cache: yes
        cache_valid_time: 3600
        state: latest

    - name: install git package
      apt:
        name: git
        update_cache: yes
        cache_valid_time: 3600
        state: latest

    - name: Create user josh
      user:
        name: josh
        shell: /bin/bash

    - name: Create user ansible
      user:
        name: ansible
        shell: /bin/bash

    - name: add Ansible ssh key
      authorized_key:
        user: josh, ansible
        state: present
        key: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICPM8xsQ9Y+s7d5cBCBDo8lleyOui7gttZqkoEP+6MNN ansible
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFyElCMNFojFX/mLWuIFAzKOzZlhJqgkxefOzQJ6bI/b josh default

    - name: add user josh to sudo group
      user:
        name: josh
        groups: sudo
        append: yes

    - name: add user ansible to sudo group
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/sudoer_ansible
        owner: root
        group: root
        mode: '0440'
