---
# This playbook updates all packages on the specified servers.
- name: Update Ubuntu servers
  hosts: proxmox_servers, media_server
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: true

    - name: Upgrade all packages
      apt:
        # 'upgrade: dist' performs a dist-upgrade, which may remove packages.
        upgrade: dist
        autoremove: true
        autoclean: true
